// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP-2IDYcViFBgv0kJlXOBPZph8cz1aoJc',
    appId: '1:642142438443:web:ae7e7b5da3935ce473d66e',
    messagingSenderId: '642142438443',
    projectId: 'pchopfinal',
    authDomain: 'pchopfinal.firebaseapp.com',
    storageBucket: 'pchopfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4NXS3Akt5DDVCCIOy776sXqiCRp0m9vc',
    appId: '1:642142438443:android:ec5b1eb720897b9473d66e',
    messagingSenderId: '642142438443',
    projectId: 'pchopfinal',
    storageBucket: 'pchopfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCese_mFKB1ZU1aPWVW4sLsBDwBcYQmoP8',
    appId: '1:642142438443:ios:aa65d02b3c477e7c73d66e',
    messagingSenderId: '642142438443',
    projectId: 'pchopfinal',
    storageBucket: 'pchopfinal.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCese_mFKB1ZU1aPWVW4sLsBDwBcYQmoP8',
    appId: '1:642142438443:ios:aa65d02b3c477e7c73d66e',
    messagingSenderId: '642142438443',
    projectId: 'pchopfinal',
    storageBucket: 'pchopfinal.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP-2IDYcViFBgv0kJlXOBPZph8cz1aoJc',
    appId: '1:642142438443:web:d0543ef03f76511273d66e',
    messagingSenderId: '642142438443',
    projectId: 'pchopfinal',
    authDomain: 'pchopfinal.firebaseapp.com',
    storageBucket: 'pchopfinal.firebasestorage.app',
  );
}
